### ISSUE TITLE
Suggestion: new Readme

### ISSUE THREAD

**Issue by rabbitix** [ChrisKneller/pygame-pathfinder#1]
hey.. i found this code from [reddit](https://www.reddit.com/r/Python/comments/g1p4ce/visualising_dijkstra_vs_dfs_vs_a_pathfinding/?utm_source=share&utm_medium=web2x) ..

i think its better to give users more details to how to use the code :D 

best regards.

**Comment by ChrisKneller** [comment]
I agree. I will work on this tomorrow. Thanks for raising.
